[package]
name = "fellm-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "fellm"
path = "src/main.rs"

[features]
default = []
backend-cuda = ["fellm-runtime/backend-cuda"]
tracy = ["dep:tracing-tracy"]

[dependencies]
fellm-architecture-diffusion-gemma = { path = "../../plugins/diffusion_gemma" }
fellm-core.workspace = true
fellm-gguf.workspace = true
fellm-tokenizer.workspace = true
fellm-runtime.workspace = true
fellm-plugin-abi.workspace = true
fellm-plugin-host.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tracing-tracy = { workspace = true, optional = true }

[lints]
workspace = true
