[package]
name = "fellm-model"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fellm-core.workspace = true
fellm-gguf.workspace = true
fellm-graph.workspace = true
fellm-plugin-abi.workspace = true
fellm-tokenizer.workspace = true
bytemuck.workspace = true
tracing.workspace = true

[lints]
workspace = true
