[package]
name = "backend-cpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fellm-core.workspace = true
fellm-plugin-abi.workspace = true
fellm-memory.workspace = true
gemm.workspace = true
pulp.workspace = true
dyn-stack.workspace = true
aligned-vec.workspace = true
thread_local.workspace = true
sysinfo.workspace = true
crossbeam-utils.workspace = true
multiversion.workspace = true
zerocopy.workspace = true
rayon.workspace = true
half.workspace = true
bytemuck.workspace = true
wide.workspace = true
tracing.workspace = true
rand.workspace = true
rand_chacha.workspace = true
raw-cpuid = "11.6.0"
smallvec.workspace = true

[dev-dependencies]
divan.workspace = true
iai-callgrind.workspace = true

[[bench]]
name = "cpu_kernels"
harness = false

[[bench]]
name = "iai_kernels"
harness = false
