[package]
name = "fellm-tokenizer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
ahash = "0.8"
chrono = "0.4.45"
fellm-core.workspace = true
fellm-gguf.workspace = true
minijinja = { version = "2.22", features = [
  "json",
  "builtins",
  "macros",
  "multi_template",
  "loop_controls",
] }
minijinja-contrib = { version = "2.22", features = ["pycompat"] }
regex = "1.13"
serde.workspace = true
serde_json.workspace = true
tokenizers = { version = "0.23.1", default-features = false, features = [
  "progressbar",
  "fancy-regex",
] }
tracing.workspace = true
